name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: Swatinem/rust-cache@v1
    - run: cargo test
    - run: cargo fmt -- --check

    # The generated parser generates tons of warnings,
    # so clippy is disabled for now.
    # TODO: figure out how to allow the parser warnings
    # - run: cargo clippy -- -Dwarnings
